version: '3.8'

services:
  order-database:
    image: mysql:8.0.22
    restart: unless-stopped
    env_file:
      - .env
    container_name: order-database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./DB/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./DB/data:/var/lib/mysql
      - ./DB/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  payment-service:
    image: payment-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}
    build:
      context: payment-service
      dockerfile: ./Dockerfile
      args:
        PAYMENT_SERVICE_PORT: ${PAYMENT_SERVICE_PORT}
    networks:
      - payment

  order-service:
    restart: unless-stopped
    image: order-service
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    build:
      context: order-service
      dockerfile: ./Dockerfile
    depends_on:
      - order-database
      - payment-service
    networks:
      - frontend
      - backend
      - payment
  web-app:
    restart: unless-stopped
    image: web-app
    ports:
      - ${WEB_APP_PORT}:80
    build:
      context: web-app
      dockerfile: ./Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - order-service
    networks:
      - frontend
networks:
  frontend:
  backend:
  payment: