export enum ORDER_STATUS {
  CREATED = 1,
  CONFIRMED = 2,
  DELIVERED = 3,
  CANCELLED = 0,
}

export enum SERVICE_EVENTS {
  CREATE_PAYMENT = 'CREATE_PAYMENT',
  REFUND_PAYMENT = 'REFUND_PAYMENT',
}
